title: MengGuyi's GPG pubkey
email: i@mengguyi.com
baseurl: ""
url: "https://pubkey.mengguyi.com"
twitter_username: mengguyi
github_username: mengguyi
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
